name: CytolyicGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://mor1.androidfilehost.com/dl/U5gZnnXMNnirKKqo-jaOIg/1602874703/8889791610682948705/MMX_2x.22.0_cmi_V12.1.3.0.RJACNXM_v12-11_9_20200929.zip
  ROM_NAME: MIUI:MiuiMix
  TZ: Asia/Kolkata
  username : ${{ secrets.USERNAME }}
  password : ${{ secrets.PASSWORD }}
  MIR: wet
  uploadto : uploads.androidfilehost.com
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'
       - name: install cyto bot :P
         env:
              TOKEN: ${{ secrets.TOKEN }}
         run: |
              sudo install telegram /usr/bin
              chmod +x $ROM_NAME/taco.sh
              . $ROM_NAME/taco.sh

       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone my sexy erfan code
         run: git clone ${{ secrets.ERFAN }}
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: start making gsis
         env:
              TOKEN: ${{ secrets.TOKEN }}
              
         run: |
               chmod +x $ROM_NAME/pizza.sh
               . $ROM_NAME/pizza.sh
       
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
