name: CytolyicGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://dllb2.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE2MDI3MDU5ODciLCJ1IjpudWxsLCJsdCI6ImRvd25sb2FkIiwicyI6Ijg4ZTc4YWVkNWNmZWUyOTQxODQ3ODZlNzNmM2QxNjQ1ZTk3Y2YwZDkxZDNjYTJjNTI4YmY5MGQxZjllMzkxOWE4ZjgxYjBhMmNjNTU2MzY2Y2IwMjJjMzc4OWU3MTU1NGZhMjA2NTg4OTc0MjQ5YjUxZDUyYTM1MzllYTAwMDZlIiwidCI6MTYwMjcxMDU3MCwic3RmcCI6IiIsInN0aXAiOm51bGx9.cNs353I0BjAU4jD050VDMhoOhGQdqufVyHF5-3wLe-E/Corvus_v10.0-R-Alpha-TheStorm-whyred-14102020-Official-1635.zip
  ROM_NAME: Generic:CorvusOS
  TZ: Asia/Kolkata
  ZIP_NAME: CorvusOS
  username : ${{ secrets.USERNAME }}
  password : ${{ secrets.PASSWORD }}
  MIR: wet
  uploadto : uploads.androidfilehost.com
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone my sexy erfan code
         run: git clone ${{ secrets.ERFAN }}
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: make some gsi bitches
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME

       
       - name: Upload A-only To afh
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-CytolyitcGSIs-Aonly.7z *-Aonly-*.img
              curl -T $ZIP_NAME-CytolyticGSIs-Aonly.7z ftp://$username:$password@$uploadto/
       
       - name: Upload A-only to 2nd mirror
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR $ZIP_NAME-CytolyticGSIs-Aonly.7z          
       - name: Zip AB and upload to AFH
         run: |
              cd ErfanGSIs/output
              zip -r $ZIP_NAME-CytolyticGSIs-AB.7z *-AB-*.img
              curl -T $ZIP_NAME-CytolyticGSIs-AB.7z ftp://$username:$password@$uploadto/
      
       - name: upload AB to 2nd mirror
         run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              cd ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer $MIR $ZIP_NAME-CytolyicGSIs-Aonly.7z
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
         
            
