name: CytolyicGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://ava4.androidfilehost.com/dl/CDp8mzrxjdlBQ2461lyuhw/1602926788/4349826312261699891/N970U1UES2BSLD_N970U1OYM2BSLD_XAR.zip
  ROM_NAME: OneUI
  TZ: Asia/Kolkata
  username : ${{ secrets.USERNAME }}
  password : ${{ secrets.PASSWORD }}
  MIR: wet
  uploadto : uploads.androidfilehost.com
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Set up python
         uses: actions/setup-python@v2
         with:
           python-version: '3.8.2'

       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone my sexy erfan code
         run: git clone ${{ secrets.ERFAN }}
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh

       - name: start building gsis   
         run: |
               chmod +x $ROM_NAME/pizza.sh
               . $ROM_NAME/pizza.sh
       
       - name: Print build info
         run: |
              cat ErfanGSIs/output/*-Aonly-*.txt
